services:
  dev-consul:
    image: hashicorp/consul
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - 8500:8500
      - 8600:8600/udp

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db-data:/data/db
    ports:
      - 27017:27017

  broker:
    image: apache/kafka
    restart: always
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker:29092,PLAINTEXT_HOST://broker:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker:29093"
      KAFKA_LISTENERS: "PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      CLUSTER_ID: "TS19uQgFRyCG/HX+IaZU5w"

  api:
    build:
      context: .
      dockerfile: ./api-service/Dockerfile
      target: final
    ports:
      - 8080:8080
    environment:
      CONSUL_URI: dev-consul:8500
      REDIS_URI: redis:6379
      KAFKA_URI: broker
      PORT: 8080
      JWT_SECRET: "secret"

  books:
    build:
      context: .
      dockerfile: ./books/Dockerfile
      target: final
    ports:
      - 8081:8081
    environment:
      PORT: 8081
      MONGODB_URI: mongodb://root:example@db:27017
      CONSUL_URI: dev-consul:8500
      KAFKA_URI: broker
      DbName: dbBooks

  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
      target: final
    ports:
      - 8082:8082
    environment:
      PORT: 8082
      MONGODB_URI: mongodb://root:example@db:27017
      CONSUL_URI: dev-consul:8500
      KAFKA_URI: broker
      DbName: dbAuth

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  db-data:
